baseurl = "https://leanehuguenot.fr"
title = "Léane Huguenot"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "lele"
  description = "Graphiste passionnée en UX/UI & identité visuelle. Création d’univers sur-mesure avec déploiement 360°, fidèle à votre direction artistique."
  # copyright = "Léane Huguenot｜ 0658912479｜leane.huguenot@gmail.com"
  sidebarAbout = [
    "Créative et passionnée, j’accompagne depuis plusieurs années entrepriseset particuliers dans la création et la réalisation de leurs projets, en freelance ou en entreprise. Spécialisée en UX/UI design, création d’identités visuelles et déploiement 360° (print, digital, salons, etc.), je veille à respecter la direction artistique tout en concevant des visuels qui leur ressemblent."
  ]

  email = "leane.huguenot@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "A propos"
  url = "about/"

  #[[params.navlinks]]
  #name = "Affiches en vrac"
  #url = "affiches/"  

  #[[params.navlinks]]
  #ame = "Contact"
  #url = "contact/"

  [params.social]
#  facebook      = "full page or profile url in facebook"
#  googleplus    = "full profile url in googleplus"
#  email         = "email@example.com"
#  twitter       = "full profile url in twitter"
  linkedin      = "https://www.linkedin.com/in/leane-huguenot/"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
#  github        = "full profile url in github"
#  gitlab        = "full profile url in gitlab"
#  youtube       = "full profile url in youtube"
  whatsapp      = "https://wa.me/+33658912479"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true